name: CI

on:
  push:
    paths:
      - src/*
      - tests/*
      - .github/workflows/CI.yml
      - Cargo.toml
  pull_request:
    paths:
      - src/*
      - tests/*
      - .github/workflows/CI.yml
      - Cargo.toml
  release:
    types: [published]

jobs:
  conventional_commits:
    name: conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webiny/action-conventional-commits@v1.1.0

  linter:
    name: linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clippy
        run: cargo clippy --all --all-features -- -D warnings

      - name: Format
        run: cargo fmt --all -- --check

  build:
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    needs: linter
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - runs-on: ubuntu-latest
            os: linux
          - runs-on: macos-latest
            os: macos
          - runs-on: windows-latest
            os: windows
            suffix: .exe

    steps:
      - uses: actions/checkout@v3

      - name: Build and install binary
        run: cargo install --path .

      - name: Run tests
        if: runner.os != 'Windows'
        working-directory: tests
        run: ./run_tests.sh

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: embin-x86_64-${{ matrix.os }}${{ matrix.suffix }}
          path: target/release/embin${{ matrix.suffix }}
          if-no-files-found: error

      - name: Set binary name
        if: github.event_name == 'release'
        run: cp target/release/embin${{ matrix.suffix }} embin-x86_64-${{ matrix.os }}${{ matrix.suffix }}

      - name: Upload binary
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: embin-x86_64-${{ matrix.os }}${{ matrix.suffix }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}