name: CI

on:
  push:
    branches:
      - main
    paths:
      - src/*
      - .github/workflows/CI.yml
      - Cargo.toml
  pull_request:
    branches:
      - main
    paths:
      - src/*
      - .github/workflows/CI.yml
      - Cargo.toml

defaults:
  run:
    shell: bash

jobs:
  conventional_commits:
    name: conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webiny/action-conventional-commits@v1.0.5

  linter:
    name: linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clippy
        run: cargo clippy --all --all-features -- -D warnings

      - name: Format
        run: cargo fmt --all -- --check

  build:
    needs: linter
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Build project (debug)
        run: cargo build

      - name: Install project (release)
        run: cargo install --path .

      - name: Check install
        run: embin --help