name: CI

on:
  push:
    paths:
      - src/*
      - .github/workflows/CI.yml
      - Cargo.toml
  pull_request:
    paths:
      - src/*
      - .github/workflows/CI.yml
      - Cargo.toml
  release:
    types: [published]

jobs:
  conventional_commits:
    name: conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webiny/action-conventional-commits@v1.1.0

  linter:
    name: linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clippy
        run: cargo clippy --all --all-features -- -D warnings

      - name: Format
        run: cargo fmt --all -- --check

  build:
    needs: linter
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - runs-on: ubuntu-latest
            os: linux
          - runs-on: macos-latest
            os: macos
          - runs-on: windows-latest
            os: win
            suffix: .exe

    steps:
      - uses: actions/checkout@v3

      - name: Build binary
        run: cargo build --release

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: embin-${{ matrix.os }}${{ matrix.suffix }}
          path: target/release/embin${{ matrix.suffix }}

      - name: Upload binary
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: embin-${{ matrix.os }}${{ matrix.suffix }}
          asset_path: target/release/embin${{ matrix.suffix }}
          upload_url: ${{ github.event.release.upload_url }}
          asset_content_type: application/octet-stream