name: CI

on:
  push:
    paths:
      - src/*
      - .github/workflows/CI.yml
      - Cargo.toml
  pull_request:
    paths:
      - src/*
      - .github/workflows/CI.yml
      - Cargo.toml
  release:
    types: [published]

jobs:
  conventional_commits:
    name: conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webiny/action-conventional-commits@v1.0.5

  linter:
    name: linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clippy
        run: cargo clippy --all --all-features -- -D warnings

      - name: Format
        run: cargo fmt --all -- --check

  build:
    needs: linter
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        os: [x86_64-unknown-linux-musl, arm-unknown-linux-musleabihf]
        runs-on: [ubuntu-latest]
        cross: [true]
        include:
          - os: x86_64-apple-darwin
            runs-on: macos-latest
            cross: false
          - os: x86_64-pc-windows-gnu
            runs-on: windows-latest
            suffix: .exe
            cross: false

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: ${{ matrix.os }}

      - name: Build Binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --target ${{ matrix.os }} --release

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: embin-${{ matrix.os }}${{ matrix.suffix }}
          path: target/${{ matrix.os }}/release/embin${{ matrix.suffix }}

      - name: Upload Binary
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: embin-${{ matrix.os }}${{ matrix.suffix }}
          asset_path: target/${{ matrix.os }}/release/embin${{ matrix.suffix }}
          upload_url: ${{ github.event.release.upload_url }}
          asset_content_type: application/octet-stream